### ISSUE TITLE
Suggestion: Recording with pywb

### ISSUE THREAD

**Issue by ikreymer** [webis-de/personal-web-archive#4]
Hi, great project! I just wanted to offer the suggestion that pywb can also do proxy mode recording:
https://pywb.readthedocs.io/en/latest/manual/configuring.html#http-s-proxy-mode

You can configure it to disable the banner, but keep the head insert (available as of pywb 2.0.4). If you keep the head insert, it will keep certain client side rewriting designed to make pages more consistent. For example, pywb fixes the Date and random number generator, performs special rewriting on video sites, such as fixing the DASH/HLS video streams. By using pywb for both capture and replay, you may be able to simplify the setup a bit as well as make captures that are more likely to replay in pywb. (If you set head_insert to false, it will behave same way as warcprox).
Happy to answer any questions about capture time rewriting.

Either way, thanks for putting this together!

**Comment by johanneskiesel** [comment]
Thanks Ilya! I'll have another look at the proxy mode, maybe I was a bit outdated on pywb when I stitched WASP together. I'll come back to you when I run in problems.

**Comment by johanneskiesel** [comment]
New version of WASP now records with pywb ;)
